version: "2"
services:
  app:
    container_name: app-a8 
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    volumes:
      - "../app/:/app"
    ports:
      - "5000:5000"
    networks: 
      - a8_net
    restart: always

networks:
  a8_net: