version: '3'

services:
    # a10app:
    #     container_name: a10app
    #     build:
    #         context: ../
    #         dockerfile: deployments/a10app.Dockerfile
    #     environment:
    #         MYSQL_ENDPOINT: mysqldb
    #         MYSQL_PASSWORD: pass
    #         MYSQL_USERT: user
    #         MYSQL_DB: A10
    #     links:
    #         - mysqldb
    #     depends_on:
    #         - mysqldb
    #     ports:
    #       - "8081:8081"
    #     networks:
    #         - a10net
    #     command: python routes.py
    #     restart: unless-stopped
    
    mysqldb:
        container_name: mysqldb
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: A10
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        networks:
            - a10net
        volumes:
           - storage-a10-database:/var/lib/mysql
           - ../db:/docker-entrypoint-initdb.d
        restart: always
        
networks:
    a10net:

volumes:
    storage-a10-database:
