version: '3'

services:

    api:
        container_name: a5_api
        build:
            context: ../
            dockerfile: deployments/Dockerfile
        ports:
            - "10005:10005"
        networks:
            - a5net
        environment:
            DB_PASSWORD: root
            DB_USER: user
            DB_PASSWORD: pass
            DB_DATABASE: a5db
            DB_PORT: 3306
            DB_HOST: mysqldb
            SECRET: secret
        depends_on:
            - mysqldb
        external_links:
            - mysqldb:mysqldb
        restart: always

    mysqldb:
        container_name: mysqldb
        image: mysql:5.7
        ports:
          - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: a5db
        networks:
            - a5net

networks:
    a5net:

volumes:
    db_data: